---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: run shell
      shell: |
        trap 'echo script_end >> test.log; rm test.pid' EXIT
        trap 'echo script_error >> test.log; rm test.pid' ERR SIGTERM SIGINT
        [ -f test.pid ] && kill -9 $(cat test.pid)
        echo $$ > test.pid
        echo -n > test.log
        echo -n > test2.log
        # you shell script is here:
        for line in $(seq 1 10); do
        echo test_line_${line} >> test.log
        sleep 5
        done
      async: 500
      poll: 0

    - name: pipe stdout
      shell: |
        lc=$(sed -n '$=' test.log)
        lc2=$(sed -n '$=' test2.log)
        ((lc > lc2)) && tail -n $((lc-lc2)) test.log | tee -a test2.log
      register: pipe
      failed_when: pipe.stdout.find('script_error') != -1
      until: pipe.stdout.find('script_end') != -1
      retries: 500
      delay: 1